metadata:
  description:
    Prediction task for venous thromboembolism incidence following hospital
    discharge
  contacts:
    - name: Robin van de Water
      github_username: rvandewater
  supported_datasets:
    - MIMIC-IV
predicates:
  hospital_admission: ???
  hospital_discharge: ???
  venous_thromboembolism:
    code:
      regex: I26|I80|O87.1|O88.2
trigger: hospital_discharge
windows:
  input:
    start: end <- hospital_admission
    end: trigger
    start_inclusive: false
    end_inclusive: true
    index_timestamp: end
    has:
      venous_thromboembolism: (1, None)
  gap:
    start: trigger
    end: start + 365 days
    start_inclusive: false
    end_inclusive: true
    has:
      venous_thromboembolism: (None, 0)
  target:
    start: gap.end
    end: start + 1095 days
    start_inclusive: false
    end_inclusive: true
    label: venous_thromboembolism
